In [1]:
import numpy as np 
import pyts 
import matplotlib.pyplot as plt
import bag2graph
# import numpy as np
np.seterr(divide='ignore', invalid='ignore')
from sklearn.preprocessing import LabelEncoder

%load_ext autoreload
%autoreload 2

In [2]:
import pyts.datasets

x_train, x_test, y_train, y_test = pyts.datasets.load_basic_motions(return_X_y=True)#fetch_ucr_dataset('Strawberry',use_cache=False,data_home=return_X_y=True)

total_labels = np.unique(y_train)
# print(total_labels)
label_map = dict(zip(total_labels, range(len(total_labels))))

temp_ytrain = []
for t in y_train:
    temp_ytrain.append(label_map[t])
temp_ytest = []
for t in y_test:
    temp_ytest.append(label_map[t])

y_test = np.array(temp_ytest)
y_train = np.array(temp_ytrain)



x_train.shape, y_train.shape, x_test.shape, y_test.shape

((40, 6, 100), (40,), (40, 6, 100), (40,))

In [3]:
b2g = bag2graph.Bag2Graph(10, 3, 3)
t = b2g.apply_bow_uni(x_train, y_train)


['aaa' 'aab' 'aac' 'aba' 'abb' 'abc' 'aca' 'acb' 'acc' 'baa' 'bab' 'bac'
 'bba' 'bbb' 'bbc' 'bca' 'bcb' 'bcc' 'caa' 'cab' 'cac' 'cba' 'cbb' 'cbc'
 'cca' 'ccb' 'ccc'] 27
Filtered 10 top words : ['abb' 'ccb' 'aca' 'baa' 'acc' 'cba' 'cca' 'bba' 'cac' 'caa']


In [36]:
adj, neighbors = b2g.get_cooc_matrix(0)
adj

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 2., 0., 0., 1., 0.],
       [1., 0., 0., 0., 3., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
adj, neighbors, edge = b2g.get_cooc_matrix(0)
adj

5 7 caa cba
5 7 caa cba
7 4 cba bba
4 5 bba caa
5 4 caa bba
4 8 bba cca
8 7 cca cba
7 5 cba caa
5 4 caa bba
4 5 bba caa
5 4 caa bba
4 4 bba bba
4 0 bba abb
0 7 abb cba
7 5 cba caa
5 0 caa abb
(array([5, 7, 4, 5, 4, 8, 7, 5, 4, 5, 4, 4, 0, 7, 5]), array([7, 4, 5, 4, 8, 7, 5, 4, 5, 4, 4, 0, 7, 5, 0]))
(11, 2) (11,)
 ->  [[0 7]
 [4 0]
 [4 4]
 [4 5]
 [4 8]
 [5 0]
 [5 4]
 [5 7]
 [7 4]
 [7 5]
 [8 7]] [1 1 1 2 1 1 3 1 1 2 1]


array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 2., 0., 0., 1., 0.],
       [1., 0., 0., 0., 3., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
neighbors[:,0], neighbors[:,1], neighbors

(array(['caa', 'cba', 'bba', 'caa', 'bba', 'cca', 'cba', 'caa', 'bba',
        'caa', 'bba', 'bba', 'abb', 'cba', 'caa'], dtype='<U3'),
 array(['cba', 'bba', 'caa', 'bba', 'cca', 'cba', 'caa', 'bba', 'caa',
        'bba', 'bba', 'abb', 'cba', 'caa', 'abb'], dtype='<U3'),
 array([['caa', 'cba'],
        ['cba', 'bba'],
        ['bba', 'caa'],
        ['caa', 'bba'],
        ['bba', 'cca'],
        ['cca', 'cba'],
        ['cba', 'caa'],
        ['caa', 'bba'],
        ['bba', 'caa'],
        ['caa', 'bba'],
        ['bba', 'bba'],
        ['bba', 'abb'],
        ['abb', 'cba'],
        ['cba', 'caa'],
        ['caa', 'abb']], dtype='<U3'))