In [1]:
import numpy as np 
import pyts 
import matplotlib.pyplot as plt
import bag2graph
# import numpy as np
np.seterr(divide='ignore', invalid='ignore')
from sklearn.preprocessing import LabelEncoder
import networkx as nx 

%load_ext autoreload
%autoreload 2

In [2]:
import pyts.datasets

x_train, x_test, y_train, y_test = pyts.datasets.load_basic_motions(return_X_y=True)#fetch_ucr_dataset('Strawberry',use_cache=False,data_home=return_X_y=True)

total_labels = np.unique(y_train)
# print(total_labels)
label_map = dict(zip(total_labels, range(len(total_labels))))

temp_ytrain = []
for t in y_train:
    temp_ytrain.append(label_map[t])
temp_ytest = []
for t in y_test:
    temp_ytest.append(label_map[t])

y_test = np.array(temp_ytest)
y_train = np.array(temp_ytrain)



x_train.shape, y_train.shape, x_test.shape, y_test.shape

((40, 6, 100), (40,), (40, 6, 100), (40,))

In [37]:
b2g = bag2graph.Bag2Graph(10, 3, 3, channel_size=x_train.shape[1])

t = b2g.apply_bow(x_train, y_train)

# multivariate_graph = b2g.get_cooc_matrix(x_train[0])

['aaa' 'aab' 'aac' 'aba' 'abb' 'abc' 'aca' 'acb' 'acc' 'baa' 'bab' 'bac'
 'bba' 'bbb' 'bbc' 'bca' 'bcb' 'bcc' 'caa' 'cab' 'cac' 'cba' 'cbb' 'cbc'
 'cca' 'ccb' 'ccc'] 27
Filtered 10 top words : ['ccb' 'bcc' 'aab' 'baa' 'cac' 'aca' 'bcb' 'abc' 'cbb' 'cba'] 

(40, 6)
shape (40, 6)


In [4]:
single_data = t[0]

single_data.shape, single_data

((6,),
 array([array(['bcb', 'cbb', 'cbb', 'abc', 'bcb', 'cbb', 'cba', 'cbb', 'cba',
               'abc', 'bcb', 'cbb', 'bcb', 'cbb', 'abc', 'bcb', 'bcb', 'cba',
               'bcb', 'cbb'], dtype='<U3')                                   ,
        array(['abc', 'bcb', 'cba', 'abc', 'cba', 'abc', 'cba', 'abc', 'bcb',
               'cba', 'abc', 'cba', 'abc', 'bcb', 'bcb', 'abc', 'cba', 'abc',
               'bcb', 'cba', 'bcb', 'cba', 'abc'], dtype='<U3')              ,
        array(['cba', 'abc', 'bcb', 'cba', 'abc', 'bcb', 'cba', 'abc', 'bcb',
               'cba', 'abc', 'cba', 'abc', 'bcb', 'cba', 'cba', 'bcb', 'cba',
               'abc', 'cba', 'abc', 'bcb', 'cba', 'bcb', 'bcb'], dtype='<U3'),
        array(['cba', 'abc', 'cba', 'abc', 'bcb', 'cbb', 'abc', 'bcb', 'cba',
               'cbb', 'bcb', 'cba', 'abc', 'bcb', 'abc', 'cba', 'bcb', 'cba',
               'bcb'], dtype='<U3')                                          ,
        array(['abc', 'cba', 'abc', 'cba', 'abc', 'cb

In [79]:
edges_with_weight = b2g.get_inx_cooc_matrix(0, 0)

['bcb' 'cbb' 'cbb' 'abc' 'bcb' 'cbb' 'cba' 'cbb' 'cba' 'abc' 'bcb' 'cbb'
 'bcb' 'cbb' 'abc' 'bcb' 'bcb' 'cba' 'bcb' 'cbb']
[[6 6 1]
 [6 8 5]
 [6 9 1]
 [7 6 3]
 [8 6 1]
 [8 7 2]
 [8 8 1]
 [8 9 2]
 [9 6 1]
 [9 7 1]
 [9 8 1]]


In [110]:
ebola = b2g.get_cooc_matrix(0)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  4.  6.  6. 21.]
 [ 0.  0.  0.  0.  0.  0. 24.  0.  0. 14.]
 [ 0.  0.  0.  0.  0.  0.  3.  3.  1.  2.]
 [ 0.  0.  0.  0.  0.  0.  7. 29.  3.  1.]]


In [111]:
import networkx as nx

G = nx.DiGraph(ebola)
# G.add_weighted_edges_from(edges_with_weight)
# nx.draw_networkx(G)
