In [1]:
import numpy as np 
import pyts 
import matplotlib.pyplot as plt
import bag2graph
# import numpy as np
np.seterr(divide='ignore', invalid='ignore')
from sklearn.preprocessing import LabelEncoder
import networkx as nx 

%load_ext autoreload
%autoreload 2

In [2]:
import pyts.datasets

x_train, x_test, y_train, y_test = pyts.datasets.load_basic_motions(return_X_y=True)#fetch_ucr_dataset('Strawberry',use_cache=False,data_home=return_X_y=True)

total_labels = np.unique(y_train)
# print(total_labels)
label_map = dict(zip(total_labels, range(len(total_labels))))

temp_ytrain = []
for t in y_train:
    temp_ytrain.append(label_map[t])
temp_ytest = []
for t in y_test:
    temp_ytest.append(label_map[t])

y_test = np.array(temp_ytest)
y_train = np.array(temp_ytrain)



x_train.shape, y_train.shape, x_test.shape, y_test.shape

((40, 6, 100), (40,), (40, 6, 100), (40,))

In [3]:
b2g = bag2graph.Bag2Graph(10, 3, 3, channel_size=x_train.shape[1])

t = b2g.apply_bow(x_train, y_train)

# multivariate_graph = b2g.get_cooc_matrix(x_train[0])

{'ccb': 0, 'bcc': 1, 'aab': 2, 'baa': 3, 'cac': 4, 'aca': 5, 'bcb': 6, 'abc': 7, 'cbb': 8, 'cba': 9}
Filtered 10 top words : ['ccb' 'bcc' 'aab' 'baa' 'cac' 'aca' 'bcb' 'abc' 'cbb' 'cba'] 

(40, 6)
shape (40, 6)


In [4]:
single_data = t[0]

single_data.shape, single_data

((6,),
 array([array(['bcb', 'cbb', 'cbb', 'abc', 'bcb', 'cbb', 'cba', 'cbb', 'cba',
               'abc', 'bcb', 'cbb', 'bcb', 'cbb', 'abc', 'bcb', 'bcb', 'cba',
               'bcb', 'cbb'], dtype='<U3')                                   ,
        array(['abc', 'bcb', 'cba', 'abc', 'cba', 'abc', 'cba', 'abc', 'bcb',
               'cba', 'abc', 'cba', 'abc', 'bcb', 'bcb', 'abc', 'cba', 'abc',
               'bcb', 'cba', 'bcb', 'cba', 'abc'], dtype='<U3')              ,
        array(['cba', 'abc', 'bcb', 'cba', 'abc', 'bcb', 'cba', 'abc', 'bcb',
               'cba', 'abc', 'cba', 'abc', 'bcb', 'cba', 'cba', 'bcb', 'cba',
               'abc', 'cba', 'abc', 'bcb', 'cba', 'bcb', 'bcb'], dtype='<U3'),
        array(['cba', 'abc', 'cba', 'abc', 'bcb', 'cbb', 'abc', 'bcb', 'cba',
               'cbb', 'bcb', 'cba', 'abc', 'bcb', 'abc', 'cba', 'bcb', 'cba',
               'bcb'], dtype='<U3')                                          ,
        array(['abc', 'cba', 'abc', 'cba', 'abc', 'cb

In [72]:
edges_with_weight = b2g.get_inx_cooc_matrix(0, 0)

In [73]:
ebola = b2g.get_cooc_matrix(0)

[array([[6, 6, 1],
        [6, 8, 5],
        [6, 9, 1],
        [7, 6, 3],
        [8, 6, 1],
        [8, 7, 2],
        [8, 8, 1],
        [8, 9, 2],
        [9, 6, 1],
        [9, 7, 1],
        [9, 8, 1]], dtype=int64) array([[6, 6, 1],
                                        [6, 7, 1],
                                        [6, 9, 4],
                                        [7, 6, 4],
                                        [7, 9, 4],
                                        [9, 6, 1],
                                        [9, 7, 7]], dtype=int64)
 array([[6, 6, 1],
        [6, 9, 6],
        [7, 6, 5],
        [7, 9, 2],
        [9, 6, 2],
        [9, 7, 7],
        [9, 9, 1]], dtype=int64) array([[6, 7, 1],
                                        [6, 8, 1],
                                        [6, 9, 3],
                                        [7, 6, 3],
                                        [7, 9, 2],
                                        [8, 6, 1],
                   

c:\Users\Arthur\Desktop\bag_to_graph\bag_of_graphs\source\bag2graph.py:147: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  edg_list = np.array(edg_list)


In [74]:
grafo1 = ebola[0]
print(grafo1)
adj_m = np.zeros((10,10))

adj_m[grafo1[:,0], grafo1[:,1]] = grafo1[:,2]

# row_sum = adj_m.sum(axis=1)

print(adj_m)

# norm_m = adj_m / row_sum[:, np.newaxis]
# np.nan_to_num(norm_m, nan = 0, copy=False)

# norm_m, row_sum

[[6 6 1]
 [6 8 5]
 [6 9 1]
 [7 6 3]
 [8 6 1]
 [8 7 2]
 [8 8 1]
 [8 9 2]
 [9 6 1]
 [9 7 1]
 [9 8 1]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 5. 1.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 2. 1. 2.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]]


In [75]:
print(grafo1, grafo1.shape)

pairs, edges = grafo1[:, :2], grafo1[:, 2].T
# print(grafo1, pairs, edges)
triplets, inx  = np.unique(grafo1[:, :1], axis=0, return_index=True)

triplets, inx


[[6 6 1]
 [6 8 5]
 [6 9 1]
 [7 6 3]
 [8 6 1]
 [8 7 2]
 [8 8 1]
 [8 9 2]
 [9 6 1]
 [9 7 1]
 [9 8 1]] (11, 3)


(array([[6],
        [7],
        [8],
        [9]], dtype=int64),
 array([0, 3, 4, 8], dtype=int64))

In [79]:
print(inx)

split_blocks = np.split(grafo1, inx[1:])
# print(split_blocks) 
print(split_blocks[0])
print(split_blocks[0].shape)
temp = split_blocks[0][:, 2]
print(temp)
row_norm = temp.sum()

print(row_norm)

kek = split_blocks[0][:,2] / row_norm
kek



[0 3 4 8]
[[6 6 1]
 [6 8 5]
 [6 9 1]]
(3, 3)
[1 5 1]
7


array([0.14285714, 0.71428571, 0.14285714])